CREATE TABLE [dbo].[StageTable]
(
    ID int NOT NULL,
    NAME VARCHAR (50) NULL,
    WEIGHT INT NULL,
    MODIFIEDDATE DATETIME DEFAULT '1900-01-01T21:15:52' ,
    TRANSACTIONTYPE VARCHAR(50) DEFAULT 'INSERT' 

)
WITH
(
    DISTRIBUTION = ROUND_ROBIN,
    CLUSTERED COLUMNSTORE INDEX
)
GO
