CREATE TABLE [dbo].[TargetTable]
(
    ID int NOT NULL,
    NAME VARCHAR (50) NULL,
    WEIGHT INT NULL,
    MODIFIEDDATE DATETIME,
    TRANSACTIONTYPE VARCHAR(50)

)
WITH
(
    DISTRIBUTION = HASH([ID]),
    CLUSTERED COLUMNSTORE INDEX
)
GO
